- packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
- packages/http-framework/src/lib/structures/Command.ts
- packages/http-framework/tests/resolvers/InteractionOptions.test.ts
Fixes the interaction argument parser for commands that have no options
> fix(interactions): handle empty options

- packages/http-framework/src/lib/Client.ts
- packages/http-framework/src/lib/interactions/index.ts
- packages/http-framework/src/lib/interactions/utils/util.ts
- packages/http-framework/src/lib/structures/Command.ts
- packages/http-framework/src/lib/structures/CommandStore.ts
This PR allows some nice stuff inside command methods:
```typescript
yield this.defer(); // null
yield this.message({ content: 'Hello there' }); // APIMessage
yield this.message({ content: 'General Kenobi!' }); // APIMessage
```
> feat: add support for response updating in commands

- packages/start-banner/README.md
Prevents overflow in npm's website
> docs(start-banner): make README's banner shorter

- packages/env-utilities/src/lib/setup.ts
- packages/env-utilities/src/lib/utils.ts
`dotenv`'s code is a hall of shame, and sets `debug` to `true` even if `options.debug` is false.
> fix(env-utilities): do not assign debug to false

- packages/http-framework/src/index.ts
- packages/http-framework/src/lib/Client.ts
- packages/http-framework/src/lib/utils/FastifyObjectOptions.ts
> refactor: cover fastify deprecated syntax

- packages/http-framework/src/lib/interactions/utils/util.ts
While I was writing a new function, I found that there was already a function that was made. i have updated the documentation.
Closes #126
> docs(http-framework): update incorrect documentation

- .npm-deprecaterc.yml
- README.md
- packages/shared-gateway-pieces/README.md
- scripts/clean.mjs
Aelia was cancelled, and Skyra v7 is planned to use HFx and therefore no project would use Gateway Pieces, so it becabe extraneous.
> refactor(shared-gateway-pieces): remove package

- .npm-deprecaterc.yml
- README.md
- packages/logger/.cliff-jumperrc.yml
- packages/logger/CHANGELOG.md
- packages/logger/README.md
- packages/logger/cliff.toml
- packages/logger/jest.config.mjs
- packages/logger/package.json
- packages/logger/src/index.ts
- packages/logger/src/lib/Logger.ts
- packages/logger/src/tsconfig.json
- packages/logger/tests/lib/Logger.test.ts
- packages/logger/tests/tsconfig.json
- packages/logger/tsconfig.eslint.json
- packages/logger/tsup.config.ts
- scripts/clean.mjs
- yarn.lock
This logger is based on Iriss's [logger](https://github.com/skyra-project/iriss/blob/aa2b53ec5a5312430434aa13295e0892d69d5089/src/lib/setup/logger.ts) and draws inspiration from [`@sapphire/plugin-logger`](https://www.npmjs.com/package/@sapphire/plugin-logger), however, it has several differences:
- It does not require `@sapphire/framework` <sup>[1](https://github.com/sapphiredev/plugins/blob/347cbdf0c792293573095ff76a2681188b936bb1/packages/logger/src/lib/Logger.ts#L1)</sup>.
- It does not depend on `@sapphire/time-utilities` <sup>[2](https://github.com/sapphiredev/plugins/blob/347cbdf0c792293573095ff76a2681188b936bb1/packages/logger/src/lib/LoggerTimestamp.ts#L1)</sup> for timestamp formatting, instead, it uses an opinionated format to reduce dependencies (and with it, CPU overhead as …
> feat(Logger): add package

- packages/http-framework/src/lib/interactions/context-menu/decorators.ts
- packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
- packages/http-framework/src/lib/structures/Command.ts
- packages/http-framework/src/lib/structures/CommandStore.ts
BREAKING CHANGE: User command options are not longer nested into `{ [interaction.name]: T }`
BREAKING CHANGE: Message command options are not longer nested into `{ [interaction.name]: T }`
> refactor: implement better context command support

- packages/http-framework/src/lib/interactions/context-menu/decorators.ts
- packages/http-framework/src/lib/utils/normalizeInput.ts
> **Note**: This is not https://github.com/skyra-project/archid-components/labels/semver%3Amajor because `normalizeContextMenuCommand` is not exported.
> fix: add type in context menu register decorators

- packages/http-framework-i18n/src/lib/registry.ts
Teryl overrides `interpolation` to add `defaultVariables`, but that accidentally removed the plugin's defaults.
> fix: do not override `options.interpolation` in `init`

- packages/http-framework/src/lib/Client.ts
- packages/http-framework/src/lib/utils/constants.ts
- packages/http-framework/src/lib/utils/streams.ts
This way, people can't take HTTP bots down by sending very large payloads.
The code is based on [`node:streams/consumers.json`](https://github.com/nodejs/node/blob/72aafbdba74d9d353f9b2d43df4072d4d061fb3f/lib/stream/consumers.js#L53-L70)
> refactor(hfx): add safe text body reader

- packages/safe-fetch/.cliff-jumperrc.yml
- packages/safe-fetch/CHANGELOG.md
- packages/safe-fetch/README.md
- packages/safe-fetch/cliff.toml
- packages/safe-fetch/package.json
- packages/safe-fetch/src/index.ts
- packages/safe-fetch/src/lib/HttpError.ts
- packages/safe-fetch/src/lib/errors/HttpError.ts
- packages/safe-fetch/src/lib/fetch.ts
- packages/safe-fetch/src/tsconfig.json
- packages/safe-fetch/tsconfig.eslint.json
- packages/safe-fetch/tsup.config.ts
- yarn.lock
Adds `@skyra/safe-fetch`, based on Teryl v1's code.
Requires Node.js v18+ and uses `@sapphire/result`, it's a heavy package compared to `@sapphire/fetch` due to the external dependency, and keeps logic simple by using FP patterns.
> feat(safe-fetch): add package

- packages/http-framework/package.json
- packages/http-framework/src/index.ts
- packages/http-framework/src/lib/Client.ts
- packages/http-framework/src/lib/ClientEvents.ts
- packages/http-framework/src/lib/structures/CommandStore.ts
- packages/http-framework/src/lib/structures/InteractionHandlerStore.ts
- yarn.lock
BREAKING CHANGE: `Client` now extends `@vladfrangu/async_event_emitter`'s AEE
> feat!: added event hooks

- .github/workflows/continuous-integration.yml
- package.json
- packages/i18next-backend/src/index.ts
- tsconfig.eslint.json
i18next made their types stricter which caused a build issue with the latest version of the library. This PR fixes that issue.
Also added a (*currently disabled*) workflow job to type check the code. It is currently disabled because @skyra/http-framework has 17 type errors. Can you fix those please @kyranet?
> fix(i18next-backend): fixed types with i18next

- packages/http-framework/src/tsconfig.json
- packages/http-framework/tests/tsconfig.json
- packages/http-framework/tsconfig.eslint.json
- packages/shared-http-pieces/src/tsconfig.json
- packages/shared-http-pieces/tsconfig.eslint.json
- packages/twitch-helpers/package.json
- packages/twitch-helpers/src/lib/twitch.ts
- packages/twitch-helpers/tsup.config.ts
- scripts/clean.mjs
- scripts/tsup.config.ts
- tsconfig.base.json
- yarn.lock
<details>
<summary>Outdated</summary>
I did the things that are supposed to fix the issue, however, the version inject doesn't seem to be working on `yarn build`, the compiled code shows:
```typescript
var packageVersion = "[VI]{{inject}}[/VI]";
```
Rather than:
```typescript
var packageVersion = "1.0.0";
```
</details>
> fix(twitch-helpers): resolve loading bugs

- packages/shared-http-pieces/src/commands/info.ts
- packages/shared-http-pieces/src/lib/information.ts
While the /info command runs fine for all bots, it doesn't for Ring as they lack of an invite link.
> refactor: handle invite-less bots

- packages/http-framework/src/lib/structures/CommandStore.ts
- packages/http-framework/src/lib/structures/InteractionHandlerStore.ts
Necessary for bots with #226 to report exceptions with the labels, as Sentry deduplicates them with the first event's extras rather than combining them.
> refactor: change error emit order

- packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
- packages/http-framework/src/lib/interactions/structures/interactions/MessageComponentUserSelectInteraction.ts
feat: added `id` to `TransformedArguments.User`
feat: added `TransformedArguments.PartialUser` for autocomplete
feat: added `TransformedArguments.PartialAttachment` for autocomplete
feat: added `TransformedArguments.PartialChannel` for autocomplete
feat: added `TransformedArguments.PartialRole` for autocomplete
feat: added `TransformedArguments.PartialAny` for autocomplete
> fix: handle `resolved`'s keys being `undefined`

- packages/twitch-helpers/src/index.ts
- packages/twitch-helpers/src/lib/twitch.ts
- packages/twitch-helpers/src/lib/variables.ts
These functions did the same but had different names. Removed one, kept the other. _technically_ a breaking change but we don't use either functions in Teryl and I doubt anyone else uses the lib anyway.
> fix(twitch-helpers): remove duplicate function

- packages/http-framework/src/lib/interactions/structures/interactions/base/BaseInteraction.ts
This PR resolves a "unknown webhook" error message appearing due possible to a race condition. This error has received multiple complaints over at the [DDevs server](https://discord.com/channels/613425648685547541/1245841059515207821), though they are not using this library. The current speculation is that the error occurs due to a race condition, where the PATCH is processed by Discord before the initial interaction reply.
I have received hundreds of 404 errors over a year and so far have received none after implementing this fix in my own fork for a week. Only thing I noticed was that average ping times have gone up by around 200ms (servers in Germany), but at least the implementation is correct.
Relevent Node.js documentation: …
> fix: possible race condition leading to 404s

- packages/env-utilities/package.json
- packages/env-utilities/src/setup.ts
- packages/env-utilities/tsup.config.ts
As you will know, dotenv has the option to execute its config function with the defaults, using the `dotenv/config` import. 
Therefore, I have added to ability to do the same with env-utilities.
```ts
import '@skyra/env-utilities/setup';
```
Both Skyra and Sapphire projects use `src/.env` so it wouldn't be very useful there. However, it would be great to have it for those (myself included) who prefer the default of it being in the root folder.
> [!NOTE]
> The only thing I haven't done is update the readme to include such. The reason is that I'm not that great with documentation and feel I would ruin the flow of how it's read.
> 
> One of those that I came up with was:
> > Alternatively, you can call setup using the dotenv defaults by using the following:
> > ```typescript
> > import …
```
> feat(env-utilities): add support for @skyra/env-utilities/setup

- .github/workflows/publish.yml
Addresses the recent permission problem that was introduced with my last PR. Long story short, adding the "id-token" permission reset all default permissions back to none.
This was first noticed with Sapphire utilities, where the following error was returned when attempting to create a release:
> Resource not accessible by integration - https://docs.github.com/rest/releases/releases#create-a-release
> ci(publish): add contents permission
